### ISSUE TITLE
382581	Acsblty - Home -> Profile -> Area of Expertise : Pressing the right arrow key doesnot moves the focus to the adjacent menu bar item to the right

### ISSUE THREAD

**Issue by ankit007pandit** [asitparida/VxGrid#102]
382581  Acsblty - Home -> Profile -> Area of Expertise : Pressing the right arrow key doesnot moves the focus to the adjacent menu bar item to the right

Expected Results

Verify that when the menu has focus, pressing the right arrow key moves the focus to the adjacent menu bar item to 
the right and pressing left arrow key moves the focus to the adjacent menu bar item to the left. 

Actual Result:
when the menu has focus, pressing the right arrow key doesnot moves the focus to the adjacent menu bar item to 
the right and pressing left arrow key doesnot moves the focus to the adjacent menu bar item to the left.

**Comment by asitparida** [comment]
Are you referring to the column menus here ?

**Comment by asitparida** [comment]
Could not repro. Please recheck behaviour @ http://vxgrid.azurewebsites.net/
