### ISSUE TITLE
382592	Acsblty - Home -> Profile -> Area of Expertise : Pressing enter, spacebar and down arrow each doesnot open the menu and places focus on the first menu item in the opened menu

### ISSUE THREAD

**Issue by ankit007pandit** [asitparida/VxGrid#103]
382592  Acsblty - Home -> Profile -> Area of Expertise : Pressing enter, spacebar and down arrow each doesnot open the menu and places focus on the first menu item in the opened menu

Test Case ID:36.3

Repro Steps
1. Open the content or service with a browser.
2. Tab until the menu has focus
3. Press the enter key
4. Press shift+tab (to move focus off of the menu)
5. Press tab to move focus back to the menu
6. Press spacebar
7. Press shift+tab (to move focus off of the menu)
8. Press down arrow

Expected Results

Verify that when the menu has focus, pressing enter, spacebar and down arrow each open the menu and places focus on 
the first menu item in the opened menu or child menu bar.

Note: this includes all menu items, even ones that are disabled. They receive focus but do not have an action when 
enter or left/right arrow is pressed. It is important that the state of the menu item be communicated to the user 
(see MAS 40 for more info).

Actual Result:

when the menu has focus:
1.Pressing Enter opens the menu but doesnot place the focus on the first menu item in the opened menu or child menu bar.
2.Pressing Spacebar opens the menu but doesnot place the focus on the first menu item in the opened menu or child menu bar
  and it is moving  to the bottom of the page
3.Pressing down arrow doesnot open the menu and the page is moving down.

Effected Controls:

Section Name: Accreditations

Name
Workshop
Accreditation Date

Section Name : Certifications

Certification Name
Organization Name
Expiration Date

**Comment by asitparida** [comment]
can you verify the behaviour @ http://vxgrid.azurewebsites.net/ ?

**Comment by asitparida** [comment]
Could not repro. Please recheck behaviour @ http://vxgrid.azurewebsites.net/
