### ISSUE TITLE
391729	Acsblty - Home -> Profile -> Accreditation : Pressing the down arrow key cycles doesnot focus through the items in the menu.

### ISSUE THREAD

**Issue by ankit007pandit** [asitparida/VxGrid#109]
391729  Acsblty - Home -> Profile -> Accreditation : Pressing the down arrow key cycles doesnot focus through the items in the menu.

Test Case ID : 36.6

Repro Steps
1. Open the content or service with a browser.
2. tab until the menu has focus
3. press enter or spacebar to open the menu
4. press the down arrow key until the end of the list is reached
5. press the down arrow key once more.

Expected Results

Verify that when the menu has focus, pressing the down arrow key cycles focus through the items in the menu, 
including all disabled menu items and when it reaches the last item, pressing the down arrow key will cycle back to 
the first menu item. Verify that similar behavior works for the up arrow key as well.

Actual Reuslt:

when the menu has focus, pressing the down arrow key cycles doesnot focus through the items in the menu.

**Comment by asitparida** [comment]
The focus is not supposed to be cycled.
