### ISSUE TITLE
391735	Acsblty - Home -> Profile -> Accreditation : Escape key doesnot close the menu when a menu is open and focus in on a menu item in that open menu

### ISSUE THREAD

**Issue by ankit007pandit** [asitparida/VxGrid#110]
391735  Acsblty - Home -> Profile -> Accreditation : Escape key doesnot close the menu when a menu is open and focus in on a menu item in that open menu

Test Case ID : 36.7

Repro Steps:
1. Open the content or service with a browser.
2. Tab until the menu has focus.
3. Press enter or spacebar to open the menu.
4. Press the escape key.

Expected Results:

Verify that when the menu is open, pressing the escape key closes the menu.

Actual Result:

Menu doesnot close on pressing escape key when the menu is open and focus is on the menu item in that open menu.

**Comment by asitparida** [comment]
Please re-check the behaviour @http://vxgrid.azurewebsites.net/

**Comment by asitparida** [comment]
Could not repro. Please recheck behaviour @ http://vxgrid.azurewebsites.net/
