### ISSUE TITLE
396147	Acsblty - Home -> Profile -> Certification : Pressing the right arrow key doesnot moves the focus to the adjacent menu bar item

### ISSUE THREAD

**Issue by ankit007pandit** [asitparida/VxGrid#111]
396147  Acsblty - Home -> Profile -> Certification : Pressing the right arrow key doesnot moves the focus to the adjacent menu bar item

Test Case ID : 36.4 

Repro Steps
1. Open the content or service with a browser.
2. Tab until the menu has focus.
3. Press the right arrow key.
4. Press the left arrow key.

Expected Results

Verify that when the menu has focus, pressing the right arrow key moves the focus to the adjacent menu bar item to 
the right and pressing left arrow key moves the focus to the adjacent menu bar item to the left. 

Actual Result:
when the menu has focus, pressing the right arrow key doesnot moves the focus to the adjacent menu bar item to 
the right and pressing left arrow key doesnot moves the focus to the adjacent menu bar item to the left.

**Comment by asitparida** [comment]
left and right arrow key are not supposed to be used for vertical traversal.
