### ISSUE TITLE
396404	Acsblty - Home -> Profile -> Certification:when a submenu is open and focus in on a menu item in the submenu then pressing escape or left arrow causes the submenu to close and returns focus to the parent menu item.

### ISSUE THREAD

**Issue by ankit007pandit** [asitparida/VxGrid#113]
396404  Acsblty - Home -> Profile -> Certification:when a submenu is open and focus in on a menu item in the submenu then pressing escape or left arrow causes the submenu to close and returns focus to the parent menu item.

Test case ID:36.9

Repro Steps
1. Open the content or service with a browser.
2. Tab until the menu has focus.
3. Press the enter key.
4. Press the down arrow key to move to a menu item with a submenu.
5. Press enter to open the submenu.
6. Press escape to close the submenu.
7. Confirm that focus returns to the parent menu.
8. Press right arrow to open the submenu.
9. Press left arrow to close the submenu. 

Expected Results

Verify that when a menu item with a submenu has focus and the submenu is open, pressing escape or left arrow closes the submenu and returns focus to the parent menu item. 

Actual Results

1.Escape does not closes the menu
2.Right arrow does not open the submenu
3.Left arrow does not close the submenu

**Comment by asitparida** [comment]
Please re-check the behaviour @http://vxgrid.azurewebsites.net/

**Comment by asitparida** [comment]
Could not repro. Please recheck behaviour @ http://vxgrid.azurewebsites.net/
