### ISSUE TITLE
Need to change pageLength dynamically (enhancement)

### ISSUE THREAD

**Issue by Shailu4u** [asitparida/VxGrid#119]
There should be pageLength dropdown in grid options, so that the user will have flexibility to see selected pageLength number of rows.

![image](https://cloud.githubusercontent.com/assets/5828578/15531244/f1320088-2276-11e6-87b4-1ff9eaf250b4.png)

Based on selected pageLength value, corresponding pagination will change dynamically.

**Comment by asitparida** [comment]
Why dont  you build it outside the plugin ? You already have the hook anyways.
