### ISSUE TITLE
 table  filters is not showing properly if table height is less or data is less

### ISSUE THREAD

**Issue by ankit007pandit** [asitparida/VxGrid#123]
full drop down height is not displayed if data is less

**Comment by Shailu4u** [comment]
Try to give sufficient fixed height to grid container always in order to work with vx grid efficiently.

**Comment by asitparida** [comment]
Use at least 50vh height for the tables.

**Comment by ankit007pandit** [comment]
but as per requirement we need container height to be auto

**Comment by asitparida** [comment]
Okay, we will caculate on runtime and apply the height. Look out here to be kept updated.
