### ISSUE TITLE
Consistency of blanks in the grids

### ISSUE THREAD

**Issue by ankit007pandit** [asitparida/VxGrid#124]
![null in filter](https://cloud.githubusercontent.com/assets/12392432/15711945/e591b7a2-282d-11e6-87bc-d9eab0df595a.png)
![blank filter](https://cloud.githubusercontent.com/assets/12392432/15711950/e9e3244e-282d-11e6-9ac3-30a48bfd8d5b.png)

observation:-
we do not have consistency in some column filter null is shown and in some column filter blank is shown

requirement:-
we should have consistency either null or blank should be shown in both column filter

**Comment by asitparida** [comment]
Well, we show 'blank' if the data == '' and 'null' if data == null
