### ISSUE TITLE
Accessibility bug : Need to add the "For" attribute and id's as well in manage columns

### ISSUE THREAD

**Issue by irfanlbrce** [asitparida/VxGrid#129]
2 bugs are logged 

_1.517319 Acsblty->GRM->MAS19->RM->RMDashboard:Manage column Screen - Level 2->Ensures every form element has a label
2.517307 Acsblty->GRM->MAS20->RM->RMDashboard:Manage column Screen - Level 2->Instructions and cues must be related to their respective input components through label, title, or ARIA attribute._

I attached the screen of updated VX-Grid

![image](https://cloud.githubusercontent.com/assets/10115931/15920856/1079742e-2e3b-11e6-8fb2-122f5046d1e0.png)

![image](https://cloud.githubusercontent.com/assets/10115931/15920965/df139fbc-2e3b-11e6-88e5-6259883e7e4e.png)

**Comment by asitparida** [comment]
This is fixed.
