### ISSUE TITLE
accessibility bug of 200% zoom 

### ISSUE THREAD

**Issue by ankit007pandit** [asitparida/VxGrid#130]
observation:-
table at 100% zoom

![vx-table at 100 zoom](https://cloud.githubusercontent.com/assets/12392432/15929973/f660e346-2e6d-11e6-80d0-efd55c943e9c.png)

table at 200% zoom columns are hidding 

![vx-grid at 200 zoom](https://cloud.githubusercontent.com/assets/12392432/15929988/0d33fb94-2e6e-11e6-9fef-b97243927752.png)

requiement:-

at 200% zoom columns should not hide

**Comment by asitparida** [comment]
Removed XS Specific styles for now. You should see scrollbars.
