### ISSUE TITLE
Loader image should load when we apply filters on the grid.

### ISSUE THREAD

**Issue by krishnanuli88** [asitparida/VxGrid#165]
Hi,

Is there any way to display the loader image on the grid, when we are doing search, sort or applying filters on the grid. 

Thanks,
Krishna.
09959654144

**Comment by asitparida** [comment]
No, if we are using the pure angular variant there is no sure shot way to do this.  
Introducing it by any means would again raise issues with respect to the sycnhronizing the DOM events
