### ISSUE TITLE
Grid is taking more time to bind more than 1000 records

### ISSUE THREAD

**Issue by krishnanuli88** [asitparida/VxGrid#217]
Hi,

When I am loading data of more than 1000+ records to the grid, it was taking more time to bind those data, during this the page was going to not responding state. Do we need to add any other extra configurations to resolve this.

Thanks,
Krishna.

**Comment by krishnanuli88** [comment]
We are finding the same issue, even in the sample application taken from GITHUB.

![sample](https://cloud.githubusercontent.com/assets/20771120/20421280/d64f5c64-ad88-11e6-9447-b14c723abfed.png)

**Comment by asitparida** [comment]
Use hybrid mode.

**Comment by krishnanuli88** [comment]
I think if we enable the hybrid mode, it will disable the pagination.

**Comment by asitparida** [comment]
You can try now. Hybrid with pagination
