### ISSUE TITLE
Filter is hiding back of grid.

### ISSUE THREAD

**Issue by tejashwiniChenna** [asitparida/VxGrid#24]
when I used pagination and have given filter option, I am able to see only one record. To change filter option or removing filter options I am not able to see complete filter and filter is going behind the grid as shown in second image.
![filter option with pagination](https://cloud.githubusercontent.com/assets/15981313/13168510/5a62cf70-d703-11e5-96a0-7a1a0d36a3e8.PNG)
![issue with after filter](https://cloud.githubusercontent.com/assets/15981313/13168511/5d14d45c-d703-11e5-8660-c13accbecab4.PNG)

**Comment by asitparida** [comment]
Not an effective utilization of the scroll area. If we have stacked tables, then I recommend not using the infinite scroll but using the pagination one. Provides a better UX. Also, please work with a minimum height of 50vh for best experience.
