### ISSUE TITLE
Select all header check box not emiting any event

### ISSUE THREAD

**Issue by bhasker412** [asitparida/VxGrid#25]
On checking and unchecking of grid header select all rows check box event is not triggering.

**Comment by bhasker412** [comment]
Please add following line of code in  allRowSelectionChanged function to solve the issue

`$scope.$emit('vxGridRowMultiSelectionChange', { 'id': $scope.vxConfig.id, 'data': $scope.vxColSettings.multiSelected });`

**Comment by asitparida** [comment]
Event Added
