### ISSUE TITLE
Expose selected records when ever required.

### ISSUE THREAD

**Issue by bhasker412** [asitparida/VxGrid#34]
Provide some kind of function or event from which we can get the selected records. This is useful when we are doing some external operations based on selected records.

If we want to use selected records data to some modal popup, with the current implementation, we have created a array and pushing emited record data on every 'vxGridRowSelectionChange' event and passing to modal. Which is reworking again to get the selected records as the grid is maintaining the selected records details.

**Comment by asitparida** [comment]
use <CONFIG>.getSelectedRows(). Check app.js for example.
