### ISSUE TITLE
for numeric column filter dropdown is not showing up.

### ISSUE THREAD

**Issue by bhasker412** [asitparida/VxGrid#35]
If a column has data of numeric type filter dropdown is not turning up at all.

![numeric column filter issue](https://cloud.githubusercontent.com/assets/4247402/13353109/fa81a6b6-dcb7-11e5-8cb8-86a79ce7a186.png)

**Comment by bhasker412** [comment]
in `$scope.headerClick` function 
change the following line of code 

'if (typeof ret !== 'undefined' && ret != null && ret != {} && typeof ret != 'object')'

*_to *_

`if (typeof ret !== 'undefined' && ret != null && ret != {} && typeof ret != 'object' && typeof ret!='number')`

and in `function getKeyedUnique(item, id, phrase) {`

change the following line of code 

`else if (typeof item != 'object') {`

**to**

`else if (typeof item != 'object' && typeof item != 'number') {`

**Comment by asitparida** [comment]
Appropriate fix provided
