### ISSUE TITLE
custom date time format is showing in filter dropdown

### ISSUE THREAD

**Issue by bhasker412** [asitparida/VxGrid#36]
I have used a cellDefn for date format its working for data in the grid but the same format is not showing in header filter.

![date format issue](https://cloud.githubusercontent.com/assets/4247402/13355428/63f35ca8-dcc6-11e5-9a5f-8c5550999c61.png)

**Comment by asitparida** [comment]
Use column prop 'filterCellDefn'. Check example in app.js
