### ISSUE TITLE
Grid not refreshed when i tried to update a column value from Angular code

### ISSUE THREAD

**Issue by MSSRamarao** [asitparida/VxGrid#48]
Grid is not showing the column value as and when I update it in the grid object. It is showing only when I refresh the browser. (Ctrl+F5)

**Comment by Shailu4u** [comment]
@MSSRamarao Re-render the grid after you update grid details using boolean in ng-if on grid container. Otherwise reload the updated data with self.vxSampleConfig.data = updated data.

**Comment by asitparida** [comment]
You would need to refresh the data for that. You can use - <config>.resetVxInstance() method

**Comment by MSSRamarao** [comment]
This is not refreshing the grid. I again need to do a hard refresh to see the change in the grid.

**Comment by MSSRamarao** [comment]
- Nelson

From: MSS Ramarao Kancherla
Sent: Thursday, March 17, 2016 9:01 PM
To: 'asitparida/VxGrid' reply@reply.github.com; asitparida/VxGrid VxGrid@noreply.github.com
Subject: RE: [VxGrid] Grid not refreshed when i tried to update a column value from Angular code (#48)

This is not refreshing the grid. I again need to do a hard refresh to see the change in the grid.

**Comment by MSSRamarao** [comment]
2 more issues:
1.      vxGridRowSelectionChange event is not fired when column filter values are checked/unchecked

Steps:
1. Grid is loaded with data
2. Apply a filter for a column, this makes grid to show only filtered records
3. select a record from the grid
4. Now reset the filter
5. This shows all the records back with previously selected records got unselected
6. But vxGridRowSelectionChange event is not fired.
1.      Field missed to identify when grid 'select all' check box is selected/unselected in vxGridRowMultiSelectionChange event

Steps;
1.      When 'Select All' check box is checked/unchecked,  grid fires vxGridRowMultiSelectionChange event. But in this event, there is no field to inform if check box is selected/unselected

Regards
Ram

From: MSS Ramarao Kancherla
Sent: Friday, March 18, 2016 1:21 AM
To: 'asitparida/VxGrid' reply@reply.github.com; 'asitparida/VxGrid' VxGrid@noreply.github.com
Cc: Nelson Paily Varghese nelvarg@microsoft.com
Subject: RE: [VxGrid] Grid not refreshed when i tried to update a column value from Angular code (#48)
- Nelson

From: MSS Ramarao Kancherla
Sent: Thursday, March 17, 2016 9:01 PM
To: 'asitparida/VxGrid' reply@reply.github.com; asitparida/VxGrid <VxGrid@noreply.github.com<mailto:VxGrid@noreply.github.com>>
Subject: RE: [VxGrid] Grid not refreshed when i tried to update a column value from Angular code (#48)

This is not refreshing the grid. I again need to do a hard refresh to see the change in the grid.
