### ISSUE TITLE
Expose an event when click on save in manage columns.

### ISSUE THREAD

**Issue by bhasker412** [asitparida/VxGrid#50]
This will be used to maintain user selected columns as user preferences. As the save is not exposed its hard to track changes of manged columns.

**Comment by asitparida** [comment]
Please use on of the following 
'vxGridSettingsChanged' - EVENT ON VX GRID SETTINGS CHANGED
'vxGridSettingsBuilt' - EVENT ON VX GRID COL SETTINGS BUILT
