### ISSUE TITLE
Field missed to identify when grid 'select all' check box is selected/unselected in vxGridRowMultiSelectionChange event

### ISSUE THREAD

**Issue by MSSRamarao** [asitparida/VxGrid#53]
When 'Select All' check box is checked/unchecked,  grid fires vxGridRowMultiSelectionChange event. But in this event, there is no field to inform if check box is selected/unselected

**Comment by asitparida** [comment]
subscribe/use the event 'vxGridRowAllSelectionChange'

**Comment by MSSRamarao** [comment]
This is helpful. 

But every time 'vxGridRowAllSelectionChange' is fired, vxGridRowMultiSelectionChange event is also fired.
