### ISSUE TITLE
when the filter is applied, and click on select all checkbox,  'multi' and 'all' events are fired

### ISSUE THREAD

**Issue by MSSRamarao** [asitparida/VxGrid#56]
1. Grid is loaded with data
2. Apply a filter for a column, this makes grid to show only filtered records
3. check 'select all' check box
   4.Both vxGridRowMultiSelectionChange and vxGridRowAllSelectionChange events are fired

**Comment by asitparida** [comment]
only 'vxGridRowAllSelectionChange' is fired now.

**Comment by asitparida** [comment]
fixed
