### ISSUE TITLE
Grid is not showing the column value as and when I update it in the grid object. It is showing only when I refresh the browser. (Ctrl+F5)

### ISSUE THREAD

**Issue by MSSRamarao** [asitparida/VxGrid#57]
Grid is not showing the column value as and when I update it in the grid object. It is showing only when I refresh the browser. (Ctrl+F5)

--resetVxInstance() is not working.. couldn't find an option to reopen the bug, so created it as a new issue.

**Comment by asitparida** [comment]
The requirements were fulfilled as part of another commit.
