### ISSUE TITLE
the checkboxes in the grid are toggled only upon clicking on the checkbox twice

### ISSUE THREAD

**Issue by RajaSuman** [asitparida/VxGrid#62]
**Repro Steps**:
1. open a page that hosts this grid.
2. make sure there is at least one record in the grid.
3. click on the checkbox on one of the records
     - the record is checked.
4. do not move the mouse at all.
5. click on the checkbox once again.
     - the checkbox is not toggled.

**Observed Results**:
1. It takes two clicks to toggle a record (when the mouse is not moved)

**Expected Results**:
1. The record should be toggled upon clicking the checkbox once.

**PS**: The toggle functionality is working as expected when the mouse is moved between clicks.

**Comment by asitparida** [comment]
Could not repro.

**Comment by RajaSuman** [comment]
I tried repro'ing it. Looks like the issue is not with movement of the mouse, but with how fast I want to toggle the checkbox. This can be repro'ed if one keeps clicking on the checkbox (continuously, with no much delay between the clicks). It will be observed that only after a couple of clicks does the checkbox toggle.
