### ISSUE TITLE
Whenever there is a blank value in one of the columns in this grid, the grid lines get crocked

### ISSUE THREAD

**Issue by RajaSuman** [asitparida/VxGrid#63]
PFA a screenshot depicting the same.
![vx-grid-blankvalueincolumn](https://cloud.githubusercontent.com/assets/18047309/14045276/dbdef6c4-f2be-11e5-9546-b49e4c9c6b23.png)

**Comment by asitparida** [comment]
cannot repro. please fix the css. 
![image](https://cloud.githubusercontent.com/assets/5743601/14415298/0821de28-ffbb-11e5-8a9e-81660412343e.png)
