### ISSUE TITLE
Column Filters are not updated as and when grid columns are updated.

### ISSUE THREAD

**Issue by MSSRamarao** [asitparida/VxGrid#64]
Steps:
1.  Grid is loaded with data
2.  Select a request to update sub status
3.  Grid column – Sub-Status is showing the new value without a browser refresh
4.  Click on the column to see if the new value is shown in the filter list to filter records with the new value

Result: New value is not shown
1.  I see new value only when I do a browser refresh (Ctrl+F5)

**Comment by asitparida** [comment]
Use  <CONFIG>.resetColumnFilters() to manually reset filters on those columns. If its prebaked into plugin, it would be too heavy.
