### ISSUE TITLE
grid is not showing data in the order it sorted by default.

### ISSUE THREAD

**Issue by bhasker412** [asitparida/VxGrid#68]
my data has 5 columns and same as grid. 
col1: id - **primary column**
col2: name
col3: max marks
col4: Obtained Marks
Col5: Rank

When i bind the data which is sorted on Rank column, the grid is displaying the data sorted on primary column.

**Comment by asitparida** [comment]
Grid will always sort on **primary column** upon getting binded.

**Comment by bhasker412** [comment]
Any way to bind sorted data to the grid directly?

**Comment by asitparida** [comment]
As of now, we don't have any such avenue nor any means to achieve the same.

**Comment by asitparida** [comment]
Closed with commits. Please use  CONFIG.sortPredicate & CONFIG.reverseSortDirection
