### ISSUE TITLE
Filters(34 filters with 4 controls)->Ensure data tables are marked up semantically and have the correct header structure

### ISSUE THREAD

**Issue by irfanlbrce** [asitparida/VxGrid#98]
![image](https://cloud.githubusercontent.com/assets/10115931/15170723/1b1e3446-1766-11e6-8807-3b7ba7411cfd.png)
[MAS40 - table Structure - aXe Tool.docx](https://github.com/asitparida/VxGrid/files/258615/MAS40.-.table.Structure.-.aXe.Tool.docx)

**Comment by asitparida** [comment]
Fixes made to the best of my knwoldege
